[env:wemos_esp32mini]
platform = espressif32
board = wemos_d1_mini32
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_port = /dev/ttyUSB0
monitor_port = /dev/ttyUSB0

lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
